### ISSUE TITLE
windows-10-activation-script

### ISSUE THREAD

**Issue by romitsutariya** [Preston-Sundar/windows-10-activation-script#4]
This script is not working.

Failed to connect with server

**Comment by prestonsn** [comment]
Just tested the script on a fresh Windows 10 install, and no connection issues were raised on my end. 
Check for issues with your VPN.

One way to debug is to ping the servers listed in the script like so:
![ping](https://user-images.githubusercontent.com/35157263/119271051-69a05a00-bbc5-11eb-8e8a-51b1557ab9dc.png)
