### ISSUE TITLE
update

### ISSUE THREAD

**Issue by amalsebastian7** [Preston-Sundar/windows-10-activation-script#5]
hi,
i just wanted to know if this still works

**Comment by prestonsn** [comment]
Are you running into any issues? Please look at this issue here: https://github.com/Preston-Sundar/windows-10-activation-script/issues/4

**Comment by amalsebastian7** [comment]
we are suposed to run this code in cmd right?

**Comment by prestonsn** [comment]
Yes, this should help: https://www.wikihow.com/Run-a-BAT-File-on-Windows
